name: weekly_challenge
description: A new challenge every week.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  go_router: ^6.2.0
  firebase_core_web: ^2.2.2
  cloud_firestore: ^4.5.1
  firebase_auth_web: ^5.2.9

  provider: ^6.0.5
  firebase_storage: ^11.1.0
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.2.3
  lottie: ^2.3.2
  easy_stepper: ^0.5.0
  shared_preferences: ^2.1.0
  permission_handler: ^10.2.0
  path_provider: ^2.0.14
  flutter_launcher_icons: ^0.13.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/
    - assets/animations/done.json


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 200 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon.png"