// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeKmD0-No1Dq03tplqt4ho5UtEtt6PCGU',
    appId: '1:496396453684:web:0a415bbaa790f326334761',
    messagingSenderId: '496396453684',
    projectId: 'weeklychallenge-4a266',
    authDomain: 'weeklychallenge-4a266.firebaseapp.com',
    storageBucket: 'weeklychallenge-4a266.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgy0fBoCiVZjdqPo5DM6AsexKem_SbZjo',
    appId: '1:496396453684:android:046566568cdcb461334761',
    messagingSenderId: '496396453684',
    projectId: 'weeklychallenge-4a266',
    storageBucket: 'weeklychallenge-4a266.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF_dtTzm3fosHw3MeeoAsd_pbqWb7GDus',
    appId: '1:496396453684:ios:8ef168e3a4bf625d334761',
    messagingSenderId: '496396453684',
    projectId: 'weeklychallenge-4a266',
    storageBucket: 'weeklychallenge-4a266.appspot.com',
    iosClientId: '496396453684-ofp3ov4q2ct8a07j60tb986em9bfcjr8.apps.googleusercontent.com',
    iosBundleId: 'com.example.weeklyChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF_dtTzm3fosHw3MeeoAsd_pbqWb7GDus',
    appId: '1:496396453684:ios:8ef168e3a4bf625d334761',
    messagingSenderId: '496396453684',
    projectId: 'weeklychallenge-4a266',
    storageBucket: 'weeklychallenge-4a266.appspot.com',
    iosClientId: '496396453684-ofp3ov4q2ct8a07j60tb986em9bfcjr8.apps.googleusercontent.com',
    iosBundleId: 'com.example.weeklyChallenge',
  );
}
